// Copies the commercial fonts into assets/fonts (gitignored) and writes
// src/theme/fonts.generated.ts. Runs on postinstall so a clone without the
// fonts still bundles, on the system font. Aeonik comes from ~/Library/Fonts;
// Argent Pixel CF (the display face) from either the extracted drop inside
// assets/fonts or ~/Library/Fonts.
import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const appDir = dirname(dirname(fileURLToPath(import.meta.url)));
const weights = ['Light', 'Regular', 'Medium'];
const libraryFonts = join(homedir(), 'Library', 'Fonts');
const targetDir = join(appDir, 'assets', 'fonts');
const generatedPath = join(appDir, 'src', 'theme', 'fonts.generated.ts');
const header = '// Generated by scripts/sync-fonts.mjs; do not edit.\n';

mkdirSync(targetDir, { recursive: true });
const entries = [];

const aeonik = weights.filter((weight) =>
  existsSync(join(libraryFonts, `Aeonik-${weight}.ttf`)),
);
if (aeonik.length === weights.length) {
  for (const weight of weights) {
    const file = `Aeonik-${weight}.ttf`;
    copyFileSync(join(libraryFonts, file), join(targetDir, file));
    entries.push(`  'Aeonik-${weight}': require('../../assets/fonts/${file}'),`);
  }
  console.log('fonts: copied 3 Aeonik weights into assets/fonts');
} else {
  console.log('fonts: Aeonik not installed on this machine; system font fallback');
}

const argentSources = [
  join(targetDir, 'Argent Pixel CF v1.0', 'OTF', 'ArgentPixelCF-Italic.otf'),
  join(libraryFonts, 'ArgentPixelCF-Italic.otf'),
];
const argent = argentSources.find((p) => existsSync(p));
if (argent) {
  copyFileSync(argent, join(targetDir, 'ArgentPixelCF-Italic.otf'));
  entries.push(
    "  'ArgentPixelCF-Italic': require('../../assets/fonts/ArgentPixelCF-Italic.otf'),",
  );
  console.log('fonts: copied Argent Pixel CF Italic into assets/fonts');
} else {
  console.log('fonts: Argent Pixel CF not found; system italic fallback');
}

writeFileSync(
  generatedPath,
  `${header}export const fontMap: Record<string, number> = {\n${entries.join('\n')}\n};\n`,
);
