// Copies the Aeonik weights from ~/Library/Fonts into assets/fonts (gitignored)
// and writes src/theme/fonts.generated.ts. Runs on postinstall so a clone
// without the commercial font still bundles, on the system font.
import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const appDir = dirname(dirname(fileURLToPath(import.meta.url)));
const weights = ['Light', 'Regular', 'Medium'];
const sourceDir = join(homedir(), 'Library', 'Fonts');
const targetDir = join(appDir, 'assets', 'fonts');
const generatedPath = join(appDir, 'src', 'theme', 'fonts.generated.ts');
const header = '// Generated by scripts/sync-fonts.mjs; do not edit.\n';

const available = weights.filter((weight) =>
  existsSync(join(sourceDir, `Aeonik-${weight}.ttf`)),
);

if (available.length === weights.length) {
  mkdirSync(targetDir, { recursive: true });
  for (const weight of weights) {
    const file = `Aeonik-${weight}.ttf`;
    copyFileSync(join(sourceDir, file), join(targetDir, file));
  }
  const entries = weights
    .map((w) => `  'Aeonik-${w}': require('../../assets/fonts/Aeonik-${w}.ttf'),`)
    .join('\n');
  writeFileSync(
    generatedPath,
    `${header}export const fontMap: Record<string, number> = {\n${entries}\n};\n`,
  );
  console.log('fonts: copied 3 Aeonik weights into assets/fonts');
} else {
  writeFileSync(generatedPath, `${header}export const fontMap: Record<string, number> = {};\n`);
  console.log('fonts: Aeonik not installed on this machine; system font fallback');
}
